# Generated by Django 2.1.4 on 2018-12-11 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=400)),
                ('date', models.CharField(max_length=255)),
                ('compensation', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=400)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='filmconnx.Position')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=400)),
                ('location', models.CharField(max_length=255)),
                ('projects', models.CharField(max_length=255)),
                ('zipcode', models.IntegerField(max_length=10)),
                ('bio', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=50)),
                ('union', models.CharField(max_length=100)),
                ('imbd', models.CharField(max_length=400)),
                ('availability', models.CharField(max_length=255)),
                ('resume', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=400)),
                ('afiliated_groups', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='filmconnx.Poster'),
        ),
    ]
