# Generated by Django 2.1.4 on 2018-12-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmconnx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poster',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
