# Generated by Django 2.1.4 on 2018-12-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmconnx', '0002_auto_20181214_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='position',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
