# Generated by Django 2.1.4 on 2018-12-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmconnx', '0004_auto_20181215_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='website',
            field=models.CharField(default=2, max_length=400),
            preserve_default=False,
        ),
    ]
