# Generated by Django 2.1.4 on 2018-12-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmconnx', '0005_poster_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='website',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
