# Generated by Django 2.1.4 on 2018-12-16 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmconnx', '0006_auto_20181215_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='filmconnx.User'),
        ),
    ]
