# Generated by Django 2.1.4 on 2018-12-17 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmconnx', '0007_jobs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='filmconnx.Poster'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_jobs', to='filmconnx.User'),
        ),
    ]
